services:
  llm_vllm:
    build:
      context: ./docker/vllm
      dockerfile: Dockerfile
    image: llm-vllm
    container_name: llm_vllm
    runtime: nvidia

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    ports:
      - "8000:8000"

    volumes:
      - ./models:/models
      - /mnt/e/hf_cache:/root/.cache/huggingface

    environment:
      - HF_HOME=/root/.cache/huggingface

    command: >
      vllm serve /models/merged/my_model
      --host 0.0.0.0
      --port 8000
      --dtype bfloat16
      --max-model-len 2048
      --gpu-memory-utilization 0.85
      --max-num-seqs 8

    restart: unless-stopped
