model:
  name: "unsloth/mistral-7b-v0.3"
  load_in_4bit: true

dataset:
  name: "HuggingFaceH4/ultrachat_200k"
  split: "train_sft[:1000]"

output:
  dir: "/models/lora/my_model"

lora:
  r: 16
  lora_alpha: 16
  lora_dropout: 0.0
  bias: "none"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  random_state: 42

training:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 4
  warmup_steps: 1
  max_steps: 10
  learning_rate: 0.0002
  bf16: true
  logging_steps: 5
  save_steps: 5
  save_total_limit: 2
  report_to: "none"
